### ISSUE TITLE
Cannot alocate memory (lzma error) while installing base system.

### ISSUE THREAD

**Issue by black-ish** [djon2003/DNS-323#10]
I'm getting the following error while installing the base system:

> Feb 25 20:04:45 debootstrap: Preparing to unpack .../traceroute_1%3a2.0.20-2+b1_armel.deb ...
> Feb 25 20:04:45 debootstrap: Unpacking traceroute (1:2.0.20-2+b1) ...
> Feb 25 20:04:45 debootstrap: dpkg-deb (subprocess): decompressing archive member: lzma error: Cannot allocate memory
> Feb 25 20:04:45 debootstrap: dpkg-deb: error: subprocess <decompress> returned error exit status 2
> Feb 25 20:04:45 debootstrap: dpkg: error processing archive /var/cache/apt/archives/traceroute_1%3a2.0.20-2+b1_armel.deb (--unpack):
> Feb 25 20:04:45 debootstrap:  subprocess dpkg-deb --fsys-tarfile returned error exit status 2

I'm not sure how to proceed here, I can smash the "continue" button as much as I want and sadly the whole installation isn't possible after that error, it's about 54% done installing the base system when the error occurs.

I haven't used Debian until now only different Linux flavours. There doesn't seem to be an option to just skip it.
Can someone help me here please?

**Comment by djon2003** [comment]
Did you select only the minimal options for installation or more? If more, I would suggest to try with the minimal requirements for installation and give a try to install those after OS installation.

What's your model? Is it a DNS-323?

**Comment by black-ish** [comment]
When I press "Install base system", which is the step after "partition disks", in the main installer window I have nothing to select it just starts doing stuff and then well I get the error happening above.
Yes it's a DNS-323 and I just saw that it's a C1 model...

**Comment by djon2003** [comment]
I meant there is a module selection step (I'm not sure the exact name) which is in the guide:
> In modules step, select: `fdisk, lvm-cfg, md+lvm, partman ext3, partman raid.`

Did you install only those or others?

**Comment by black-ish** [comment]
Ah ok, I only use "cfdisk", "parted", "partman-auto" and "partman-ext3".
I'm not using any type of raid hence why I'm not selecting anything like "lvm" oder "md".

**Comment by djon2003** [comment]
Did you mean "fdisk" instead of "cfdisk"?

How many HDD do you have in it?

**Comment by black-ish** [comment]
No, I meant "cfdisk", when I selected "fdisk" no disk was detected hence I couldn't partition anything.
Currently there is 1 1TB HDD in it.

**Comment by black-ish** [comment]
Nvm, I figured it out, maybe.
I haven't done this in forever but I skipped creating a swap partition.
Forgot about it at one point.
At least I got further by now. 

Thanks for helping :)

**Comment by djon2003** [comment]
Excellent to hear! Didn't help a lot, but it's quite hard to figure without seeing the whole picture. If you have something else, don't hesitate to open another issue. And if you like the guide, you could be the first one to give a star on it.

Have a great day and fun with your updated device.
