### ISSUE TITLE
No mkinitramfs and busbox fails to be authenticated.

### ISSUE THREAD

**Issue by black-ish** [djon2003/DNS-323#11]
Hello again!
Sorry to trouble again...

After solving my first issue it seems another crops up again.

About at the point where I'm supposed to edit "/target/usr/sbin/mkinitramfs' it seems I can't go further.
To be clear here, I'm stopping at the kernel selection leaving it open and am trying to edit/locate the file in another SSH window.
The file does not exist. And after skipping the step and selecting the kernel that is mentioned in the guide I get the following error:

> Feb 26 18:59:00 in-target:
> Feb 26 18:59:02 in-target: The following NEW packages will be installed:
> Feb 26 18:59:02 in-target:   busybox
> Feb 26 18:59:03 in-target: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Feb 26 18:59:03 in-target: Need to get 374 kB of archives.
> Feb 26 18:59:03 in-target: After this operation, 796 kB of additional disk space will be used.
> Feb 26 18:59:03 in-target: WARNING: The following packages cannot be authenticated!
> Feb 26 18:59:03 in-target:   busybox
> Feb 26 18:59:03 in-target: E
> Feb 26 18:59:03 in-target: :
> Feb 26 18:59:03 in-target: There are problems and -y was used without --force-yes
> Feb 26 18:59:03 in-target:
> Feb 26 18:59:05 base-installer: error: exiting on error base-installer/kernel/failed-package-install

I'm not sure how to solve this, as I basically never use apt.

**Comment by djon2003** [comment]
Well... The `mkinitramfs` should exist, I think. 

1- Do you have files under `/target/usr/sbin/`?
2- Did you execute the `date` command as in the guide?
3- You can inspire you from https://github.com/djon2003/DNS-323/tree/2.1-After-RAID-resync. There is a hack I did. Search for: "apt_opts".

**Comment by black-ish** [comment]
Hey, thx for answering :)

1. Yes there are files in it.
2. Yes I did
3. It works with the hack.

Ok I think the guide needs to be updated:
The step of editing the "mkinitramfs" has to come after selecting the kernel, the installer will then download the necessary files for the initrd.
Also the "--force-yes" still needs to be included before installing the base system, as it fail on multiple steps, first the busybox and after it there are more packages where it would fail without the "--force-yes" option included.
If I find anything after that I will add another comment.

**Comment by black-ish** [comment]
Hmm... 
It seems I can't get further after executing "./lib/chroot-setup.sh" which needed the executing bit set, otherwise I got permission denied.
I can set the MODULES=loaded in both files but `chroot /target lsmod | cut -f 1 -d\  > /target/etc/initramfs-tools/modules` gives me the following error:

> libkmod: ERROR ../libkmod/libkmod-module.c:1638 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
> Error: could not get list of modules: No such file or directory

Maybe something went wrong in setting up the chroot?

**Comment by djon2003** [comment]
Did you see there is a space between the dot and the path? `. /lib/chroot-setup.sh`
This script is not intended to be executed, but sourced.
**Oh shoot, it is missing something there**

Concerning updating the guide, I would wait up to you successfully install Debian and even then, it would be another path, because there are at least two persons who succeeded with those steps: me and some else who afterward suggested me the Freexian update links.

**Comment by djon2003** [comment]
I added a missing step right after `. /lib/chroot-setup.sh`.

By the way, if you want to start over and try the block between the step mentioned the line above up to `chroot_cleanup` right after I say *STOP* in the guide instead of the current SSH-i block. Maybe this could fix the need to hack `apt`. Maybe not.

**Comment by black-ish** [comment]
Ok I'm now to the step where I can press "Make the system bootable" and did not press Enter yet.
I sourced `/lib/chroot-setup.sh` and wanted to execute `chroot_setup` but it doesn't exist.

**Comment by djon2003** [comment]
1. Can you execute
`cat /lib/chroot-setup.sh` and give me the result? 

Maybe the place I took the name of the function `chroot_setup` is too recent or not the proper version. I extracted it from a Git repo as I don't have access to this anymore. well, not easily.

2. Did you try over without the apt hack?

**Comment by black-ish** [comment]
> # Setup for using apt to install packages in /target.
> 
> mountpoints () {
>         cut -d" " -f2 /proc/mounts | sort | uniq
> }
> 
> # Make sure mtab in the chroot reflects the currently mounted partitions.
> update_mtab() {
>         mtab=/target/etc/mtab
> 
>         if [ -h "$mtab" ]; then
>                 logger -t $0 "warning: $mtab won't be updated since it is a symlink."
>                 return 0
>         fi
> 
>         egrep '^[^ ]+ /target' /proc/mounts | (
>         while read devpath mountpoint fstype options n1 n2 ; do
>                 devpath=`mapdevfs $devpath || echo $devpath`
>                 mountpoint="${mountpoint#/target}"
>                 # mountpoint for root will be empty
>                 if [ -z "$mountpoint" ] ; then
>                         mountpoint="/"
>                 fi
>                 echo $devpath $mountpoint $fstype $options $n1 $n2
>         done ) > $mtab
> }
> 
> divert () {
>         chroot /target dpkg-divert --quiet --add --divert "$1.REAL" --rename "$1"
> }
> 
> undivert () {
>         rm -f "/target$1"
>         chroot /target dpkg-divert --quiet --remove --rename "$1"
> }
> 
> chroot_setup () {
>         # Bail out if directories we need are not there
>         if [ ! -d /target/sbin ] || [ ! -d /target/usr/sbin ] || \
>            [ ! -d /target/proc ]; then
>                 return 1
>         fi
>         if [ -d /sys/devices ] && [ ! -d /target/sys ]; then
>                 return 1
>         fi
> 
>         if [ -e /var/run/chroot-setup.lock ]; then
>                 cat >&2 <<EOF
> apt-install or in-target is already running, so you cannot run either of
> them again until the other instance finishes. You may be able to use
> 'chroot /target ...' instead.
> EOF
>                 return 1
>         fi
>         touch /var/run/chroot-setup.lock
> 
>         # Create a policy-rc.d to stop maintainer scripts using invoke-rc.d
>         # from running init scripts. In case of maintainer scripts that don't
>         # use invoke-rc.d, add a dummy start-stop-daemon.
>         cat > /target/usr/sbin/policy-rc.d <<EOF
> #!/bin/sh
> exit 101
> EOF
>         chmod a+rx /target/usr/sbin/policy-rc.d
> 
>         if [ -e /target/sbin/start-stop-daemon ]; then
>                 divert /sbin/start-stop-daemon
>         fi
>         cat > /target/sbin/start-stop-daemon <<EOF
> #!/bin/sh
> echo 1>&2
> echo 'Warning: Fake start-stop-daemon called, doing nothing.' 1>&2
> exit 0
> EOF
>         chmod a+rx /target/sbin/start-stop-daemon
> 
>         # If Upstart is in use, add a dummy initctl to stop it starting jobs.
>         if [ -x /target/sbin/initctl ]; then
>                 divert /sbin/initctl
>                 cat > /target/sbin/initctl <<EOF
> #!/bin/sh
> if [ "\$1" = version ]; then exec /sbin/initctl.REAL "\$@"; fi
> echo 1>&2
> echo 'Warning: Fake initctl called, doing nothing.' 1>&2
> exit 0
> EOF
>                 chmod a+rx /target/sbin/initctl
>         fi
> 
>         # Record the current mounts
>         mountpoints > /tmp/mount.pre
> 
>         case `udpkg --print-os` in
>                 "linux")
>                         # Some packages (eg. the kernel-image package) require a mounted
>                         # /proc/. Only mount it if not mounted already
>                         if [ ! -f /target/proc/cmdline ]; then
>                                 mount -t proc proc /target/proc
>                         fi
> 
>                         # For installing >=2.6.14 kernels we also need sysfs mounted
>                         # Only mount it if not mounted already
>                         if [ ! -d /target/sys/devices ]; then
>                                 mount -t sysfs sysfs /target/sys
>                         fi
> 
>                         # In Lenny, /dev/ lacks the pty devices, so we need devpts mounted
>                         if [ ! -e /target/dev/pts/0 ]; then
>                                 mkdir -p /target/dev/pts
>                                 mount -t devpts devpts -o noexec,nosuid,gid=5,mode=620 \
>                                         /target/dev/pts
>                         fi
> 
>                         if ! mountpoints | grep -q '^/target/run$'; then
>                                 mount --bind /run /target/run
>                         fi
>                 ;;
>                 "kfreebsd")
>                         # Some packages (eg. the kernel-image package) require a mounted
>                         # /proc/. Only mount it if not mounted already
>                         if [ ! -f /target/proc/cmdline ]; then
>                                 mount -t linprocfs proc /target/proc
>                         fi
>                         # Some package might need sysfs mounted
>                         # Only mount it if not mounted already
>                         if [ ! -d /target/sys/devices ]; then
>                                 mount -t linsysfs sysfs /target/sys
>                         fi
>                 ;;
>         esac
> 
>         mountpoints > /tmp/mount.post
> 
>         update_mtab
> 
>         # Try to enable proxy when using HTTP.
>         # What about using ftp_proxy for FTP sources?
>         RET=$(debconf-get mirror/protocol || true)
>         if [ "$RET" = "http" ]; then
>                 RET=$(debconf-get mirror/http/proxy || true)
>                 if [ "$RET" ]; then
>                         http_proxy="$RET"
>                         export http_proxy
>                 fi
>         fi
> 
>         # Pass debconf priority through.
>         DEBIAN_PRIORITY=$(debconf-get debconf/priority || true)
>         export DEBIAN_PRIORITY
> 
>         LANG=${IT_LANG_OVERRIDE:-$(debconf-get debian-installer/locale || true)}
>         export LANG
>         export PERL_BADLANG=0
> 
>         # Unset variables that would make scripts in the target think
>         # that debconf is already running there.
>         unset DEBIAN_HAS_FRONTEND
>         unset DEBIAN_FRONTEND
>         unset DEBCONF_FRONTEND
>         unset DEBCONF_REDIR
>         # Avoid debconf mailing notes.
>         DEBCONF_ADMIN_EMAIL=""
>         export DEBCONF_ADMIN_EMAIL
>         # Avoid apt-listchanges doing anything.
>         APT_LISTCHANGES_FRONTEND=none
>         export APT_LISTCHANGES_FRONTEND
>         # Sometimes sudo may need to be removed (e.g. when installing
>         # sudo-ldap).  There's no situation in which doing this during d-i
>         # is a problem, so unconditionally override the guard in sudo.prerm.
>         SUDO_FORCE_REMOVE=yes
>         export SUDO_FORCE_REMOVE
> 
>         return 0
> }
> 
> chroot_cleanup () {
>         rm -f /target/usr/sbin/policy-rc.d
>         undivert /sbin/start-stop-daemon
>         if [ -x /target/sbin/initctl.REAL ]; then
>                 undivert /sbin/initctl
>         fi
> 
>         # Undo the mounts done by the packages during installation.
>         # Reverse sorting to umount the deepest mount points first.
>         # Items with count of 1 are new.
>         for dir in $( (cat /tmp/mount.pre /tmp/mount.pre; mountpoints ) | \
>                      sort -r | uniq -c | grep "^[[:space:]]*1[[:space:]]" | \
>                      sed "s/^[[:space:]]*[0-9][[:space:]]//"); do
>                 if ! umount $dir; then
>                         logger -t $0 "warning: Unable to umount '$dir'"
>                 fi
>         done
>         rm -f /tmp/mount.pre /tmp/mount.post
> 
>         rm -f /var/run/chroot-setup.lock
> }
> 
> # Variant of chroot_cleanup that only cleans up chroot_setup's mounts.
> chroot_cleanup_localmounts () {
>         rm -f /target/usr/sbin/policy-rc.d
>         undivert /sbin/start-stop-daemon
>         if [ -x /target/sbin/initctl.REAL ]; then
>                 undivert /sbin/initctl
>         fi
> 
>         # Undo the mounts done by the packages during installation.
>         # Reverse sorting to umount the deepest mount points first.
>         # Items with count of 1 are new.
>         for dir in $( (cat /tmp/mount.pre /tmp/mount.pre /tmp/mount.post ) | \
>                      sort -r | uniq -c | grep "^[[:space:]]*1[[:space:]]" | \
>                      sed "s/^[[:space:]]*[0-9][[:space:]]//"); do
>                 if ! umount $dir; then
>                         logger -t $0 "warning: Unable to umount '$dir'"
>                 fi
>         done
>         rm -f /tmp/mount.pre /tmp/mount.post
> 
>         rm -f /var/run/chroot-setup.lock
> }

**Comment by black-ish** [comment]
Yea it looks like a function.
Oh is it because we're using a function of a script so there is no autocomplete for it and it has to be fully typed?
I never used it that way...

Yea seems like it... "facepalms"

**Comment by black-ish** [comment]
Ok I finished the installation!!

For crying out loud that was so many facepalms for me I can't even count them (⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)

**Comment by djon2003** [comment]
I am satisfied you completed the installation. Don't worry, I had my own facepalms... and a lot too.

P.S. If you wish, you could put a star on my repository. Thank you!

**Comment by black-ish** [comment]
One thing though that needs to be changed in the guide is:

> Continue up to install base system.
> 
> STOP on kernel choice.
> SSH-b nano /target/usr/sbin/mkinitramfs:
> 
> Search for MODULES=most.
> Comment all the "case" lines except auto_add_modules.
> SSH-i In install base system.
> 
> Choose linux-image-orion5x.

Needs to be something like this:

> Continue up to install base system.
> 
> Select kernel.
> 
> Choose linux-image-orion5x.
> 
> After the next question do:
> 
> SSH-b nano /target/usr/sbin/mkinitramfs:
> 
> Search for MODULES=most.
> Comment all the "case" lines except auto_add_modules.
> SSH-i In install base system.

The `mkinitramfs` doesn't exist before the kernel is selected, the installer will pull the packages only after selecting the kernel.

**Comment by djon2003** [comment]
Thank you! I will adjust the guide. I made the guide after I successfully installed it, but still I was taking notes during my attempts. So, it is possible that I incorrectly ordered something.

As soon as I have a minute, I will update it.
