### ISSUE TITLE
Current netboot.img

### ISSUE THREAD

**Issue by 0b1001101** [djon2003/DNS-323#7]
http://archive.debian.org/debian/dists/wheezy/main/installer-armel/current/images/orion5x/network-console/d-link/dns-323/netboot.img supersedes https://ftp.nl.debian.org/debian/dists/jessie/main/installer-armel/current/images/orion5x/network-console/d-link/dns-323/netboot.img in https://github.com/djon2003/DNS-323#replacing-original-firmware

**Comment by djon2003** [comment]
Thank you for raising this issue. I just fixed it.
